import './globals.css'
import { Inter } from 'next/font/google'
import {AuthProvider} from "@/lib/context/AuthContext";
import React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Fieldwork App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <AuthProvider>
      <body className={inter.className}>{children}</body>
    </AuthProvider>
    </html>
  )
}
